Encode data payloads as UTF-8
artefactual-labs/amclient pull request #22
Opened 2022-09-07 20:16 UTC by helrond

Encodes data payloads as UTF-8.

fixes archivematica/Issues#1569

2022-09-15 20:22 UTC, tw4l requested changes
Hi @helrond, thank you for the issue and the PR! :) Overall it looks great and we appreciate the contribution.

I have two thoughts:

1. I'm wondering if it might be good to use [six.ensure_binary](https://six.readthedocs.io/#six.ensure_binary) rather than `.encode()` for Python 2/3 compatibility, e.g. to avoid an `AttributeError` if someone passes in a file object opened in bytes mode in Python 3.
2. What happens if someone passes in a non-utf-8 CSV? I think we'll get a `UnicodeEncodingErrror` and I'm wondering if we might be able to add a try/except block here to raise a more helpful error message with the exception. I know it's a recurring problem we've seen with AtoM clients of people not realizing the CSVs they generate e.g. from Excel aren't utf-8.

2022-09-16 15:24 UTC, tw4l approved these changes

2022-09-16 15:24 UTC, tw4l commented
hi @helrond - changing this to approve so that you can go ahead and make changes on your own time but I won't block other Artefactual devs from being able to merge this in :)

2022-09-16 20:31 UTC, helrond commented
Thanks for your help on this @tw4l!

I updated the line that's using `encode` to instead use `six.ensure_binary`.

Files which are not UTF-encoded will actually blow up at the `data = file_obj.read()` line with a `UnicodeDecodeError`. IMO that's what I'd expect to happen; I can always re-raise with an additional error message but that feels a little overkill to me.

2022-09-21 02:11 UTC, tw4l commented
@helrond thanks for note and the six change! LGTM

not sure I can/should merge anymore - @scollazo or @djjuhasz , would you mind doing the honors?

2022-09-21 06:04 UTC, merged

2022-09-21 06:05 UTC, scollazo commented
Merged. Thanks @helrond and @tw4l !

2022-09-21 13:18 UTC, helrond commented
Would you be able to push a new release to PyPI? Thanks!

2022-09-21 15:07 UTC, sromkey commented
@sevein could you help with PyPI when you get a chance?